### ISSUE TITLE
Allow customization of cell clicked event

### ISSUE THREAD

**Issue by liefeld** [jheatmap/jheatmap#15]
I would like to be able to customize what happens when I click on a cell (e.g. add all column annotations to the popup and maybe put links to other sites there etc).  As a stopgap in my local I added a config option called 'cellClicked' which takes a function with this definition clickOnCell(row, col, heatmap, boxTop, boxLeft, details) and then modified jheatmap.components.CellBodyPanel.onMouseUp to call this function after it calculates which cell was clicked on in the canvas.  The row/col are the indices, the heatmap is the heatmap object, boxTop and boxLeft are the position where the default popup would be and the details is the same div used by default.

**Comment by jordeu** [comment]
Related issue #8
